Projects/admin/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('test', function () {
    $data = \App\Models\ServiceCharge::select('budget_quarterly_payment')->cursor();
    $results = [];
    foreach ($data as $d) {
        if (! is_numeric($d->budget_quarterly_payment) && $d->budget_quarterly_payment != '' && ! is_null($d->budget_quarterly_payment) && ! empty($d->budget_quarterly_payment)) {
            $results[] = $d->budget_quarterly_payment;
        }
    }

    dd($results);
});

Route::middleware(['auth', 'client'])->namespace('Admin')->domain('admin.'.config('app.host'))->group(function () {
    Route::redirect('/', '/properties', 301);

    //Diary
    Route::middleware(['diary'])->group(function () {
        Route::resource('diary', 'DiaryController'); //->only(['index'])
        Route::get('diary/typeId/{id}', 'DiaryController@index')->name('diary.type');
    });

    Route::post('property/alert', 'AlertController@store')->name('property.alert.create');
    Route::delete('property/alert-delete', 'AlertController@destroy');

    Route::resource('properties', 'PropertyController');
    Route::get('overview/{date?}', 'PropertyController@overview')->name('properties.overview');
    Route::get('properties/{property}/duplicate', 'PropertyController@duplicate')->name('properties.duplicate');
    Route::post('properties/{property}/dispose', 'PropertyController@dispose')->name('properties.dispose');
    Route::resource('properties.payments', 'PaymentController');
    Route::resource('properties.utilities', 'UtilityController');
    Route::resource('properties.rents', 'RentController')->only(['create', 'store']);
    Route::resource('properties.documents', 'PropertyDocumentController'); /*->only('store')*/

    Route::resource('properties.service-charges', 'ServiceChargeController');
    Route::resource('properties.rent-reviews', 'RentReviewController')->only(['create', 'store']);
    Route::resource('properties.breaks', 'BreakController')->only(['create', 'store']);
    Route::resource('properties.client-queries', 'ClientQueryController')->only(['create', 'store']);
    Route::resource('properties.maintenances', 'MaintenanceController')->only(['create', 'store']);
    Route::resource('properties.notes', 'NoteController')->only('store');
    Route::resource('properties.insurances', 'InsuranceController')->only(['create', 'store']);
    Route::get('property/search', 'PropertyController@search');
    Route::post('property/rediarise', 'PropertyController@reDiarise')->name('rediarise');
    Route::get('property/filter-note', 'PropertyController@filterNote');
    Route::get('property/load-template-data/{id}', 'PropertyController@loadTemplateData');
    Route::get('property/attach-to/{id}', 'PropertyController@attachTo');

    Route::middleware(['agent'])->group(function () {
        Route::get('ajax/agents/{agent}/contacts/select', 'AgentController@getContactsSelectPartial')
            ->name('ajax.agents.contacts.select');
        Route::resource('agents', 'AgentController');

        Route::get('ajax/agents/{agent}/contacts/create', 'ContactController@ajaxCreate')
            ->name('ajax.agents.contacts.create');
        Route::resource('agents.contacts', 'ContactController')->only(['create', 'store']);
        Route::resource('agents.notes', 'NoteController')->only('store');
    });

    Route::resource('landlords', 'LandlordController');
    Route::resource('landlords.contacts', 'ContactController')->only(['create', 'store']);
    Route::resource('landlords.notes', 'NoteController')->only('store');

    Route::get('clients/{client}/audit-registers-partial', 'ClientController@viewAuditRegistersPartial');
    Route::resource('clients', 'ClientController');
    Route::resource('clients.contacts', 'ContactController')->only(['create', 'store']);
    Route::resource('clients.notes', 'NoteController')->only('store');

    Route::resource('contacts', 'ContactController');
    Route::resource('contacts.notes', 'NoteController')->only('store');

    Route::resource('payments', 'PaymentController')->only(['index', 'edit', 'update', 'destroy']);
    Route::resource('utilities', 'UtilityController')->only(['index', 'edit', 'update', 'destroy']);
    Route::resource('payments.documents', 'DocumentController')->only('store');
    Route::get('ajax/payments/{payment}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.payments.documents.create');

    Route::resource('rents', 'RentController')->only(['edit', 'update', 'destroy']);

    Route::resource('service-charges', 'ServiceChargeController');
    Route::resource('service-charges.documents', 'DocumentController')->only('store')->parameters([
        'service-charges' => 'serviceCharge',
    ]);
    Route::get('ajax/service-charges/{serviceCharge}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.service-charges.documents.create');

    Route::resource('rent-reviews', 'RentReviewController')->only(['edit', 'update']);
    Route::resource('rent-reviews.documents', 'DocumentController')->only('store')->parameters([
        'rent-reviews' => 'rentReview',
    ]);
    Route::get('ajax/rent-reviews/{rentReview}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.rent-reviews.documents.create');

    Route::resource('breaks', 'BreakController')->only(['edit', 'update', 'destroy']);
    Route::resource('breaks.documents', 'DocumentController')->only('store');
    Route::get('ajax/breaks/{break}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.breaks.documents.create');

    Route::resource('client-queries', 'ClientQueryController')->only(['edit', 'update']);
    Route::resource('client-queries.documents', 'DocumentController')->only('store')->parameters([
        'client-queries' => 'clientQuery',
    ]);
    Route::get('ajax/client-queries/{clientQuery}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.client-queries.documents.create');

    Route::resource('insurances', 'InsuranceController')->only(['edit', 'update', 'destroy']);
    Route::resource('insurances.documents', 'DocumentController')->only('store');
    Route::get('ajax/insurances/{insurance}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.insurances.documents.create');

    Route::resource('maintenances', 'MaintenanceController')->only(['edit', 'update']);
    Route::resource('maintenances.photos', 'MaintenancePhotoController')->only('store');
    Route::resource('maintenances.documents', 'DocumentController')->only('store');
    Route::get('ajax/maintenances/{maintenance}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.maintenances.documents.create');

    Route::resource('documents', 'DocumentController');

    Route::get('ajax/suppliers/{supplier}/contacts/select', 'SupplierController@getContactsSelectPartial')
        ->name('ajax.suppliers.contacts.select');
    Route::resource('suppliers', 'SupplierController');

    Route::get('ajax/suppliers/{supplier}/contacts/create', 'ContactController@ajaxCreate')
        ->name('ajax.suppliers.contacts.create');
    Route::resource('suppliers.contacts', 'ContactController')->only(['create', 'store']);
    Route::resource('suppliers.notes', 'NoteController')->only('store');

    Route::resource('administrators', 'AdministratorController');
    Route::resource('administrators.contacts', 'ContactController')->only(['create', 'store']);

    Route::resource('audit-registers', 'AuditRegisterController');

    Route::resource('claims', 'ClaimController');
    Route::resource('claims.notes', 'NoteController')->only('store');

    Route::get('claim-types/{claimType}/subtypes-partial', 'ClaimTypeController@viewSubtypesPartial');

    Route::resource('auditors', 'AuditorController');

    Route::resource('settings', 'SettingsController')->only('index');
    Route::post('settings/type', 'SettingsController@postType')->name('settings.type');
    Route::put('settings/type', 'SettingsController@updateType')->name('settings.update-type');
    Route::delete('settings/type', 'SettingsController@deleteType')->name('settings.delete-type');

    Route::resource('settings/currencies', 'CurrencyController');
    Route::get('settings/currencies/{currency}/delete', 'CurrencyController@delete');

    Route::resource('settings/payment-types', 'PaymentTypeController');
    Route::get('settings/payment-types/{paymentType}/delete', 'PaymentTypeController@delete');

    Route::resource('settings/claim-subtypes', 'ClaimSubtypeController');
    Route::get('settings/claim-subtypes/{claimSubtype}/delete', 'ClaimSubtypeController@delete');

    Route::resource('settings/staff', 'SettingsStaffController')->except('destroy')->middleware('superAdmin');

    Route::get('index-table', 'SettingsController@indexTable');
    Route::get('show-type/{id}', 'SettingsController@showType');
    Route::post('type-store', 'SettingsController@storeType')->name('type.store');
    Route::put('type-update', 'SettingsController@updateType')->name('type.update');
    Route::delete('type-delete', 'SettingsController@destroyType')->name('type.delete');

    // issue with this routes
    Route::middleware(['superAdmin'])->group(function () {
        Route::get('/account/settings', 'SettingsController@index')->name('account.settings');
        Route::get('/account/settings/user/{id}', 'SettingsController@userDetails')->name('user.details');
        Route::get('/account/settings/user/edit/{id}', 'SettingsController@userDetailsEdit')->name('user.details.edit');
    });

Projects/admin/app/Models/Maintenance.php
<?php

namespace App\Models;

use App\Traits\CreateAndUpdateTrait;
use App\Traits\DocumentTrait;

/**
 * Class Maintenance.
 * @version October 29, 2019, 3:32 am UTC
 *
 * @property int property_id
 * @property int diary_id
 * @property string|\Carbon\Carbon notice_date
 * @property string notes
 * @property bool resolved
 * @property int created_by
 * @property int updated_by
 */
class Maintenance extends BaseModel
{
    use CreateAndUpdateTrait, DocumentTrait;

    public $table = 'maintenance';
    public $documentStoreRoute = 'maintenances.documents.store';
    public $modelNameHuman = 'Maintenance';

    public $fillable = [
        'property_id',
        'diary_id',
        'notice_date',
        'notes',
        'resolved',
        'created_by',
        'updated_by',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'property_id' => 'integer',
        'diary_id' => 'integer',
        'notice_date' => 'datetime',
        'notes' => 'string',
        'resolved' => 'boolean',
        'created_by' => 'integer',
        'updated_by' => 'integer',
    ];

    public function property()
    {
        return $this->belongsTo(Property::class);
    }

    public function diary()
    {
        return $this->belongsTo(Diary::class);
    }

    public function saveData($data, $id = null)
    {
        if ($id) {
            $this
                ->where('id', '=', $id)
                ->update($data);
        } else {
            $id = $this
                ->insertGetId($data);
        }

        return $id;
    }

    public function maintenancePhotos()
    {
        return $this->hasMany(MaintenancePhoto::class, 'maintenance_id');
    }

    public function getAllMaintenaceByPropertyId($propertyId)
    {
        $maintenance = self::with('maintenancePhotos')
            ->where('property_id', '=', $propertyId)
            ->orderBy('notice_date', 'desc')
            ->get();

        return $maintenance;
    }

    public function getAllUnresolvedMaintenaceByPropertyId($propertyId)
    {
        $maintenance = self::where('property_id', '=', $propertyId)
            ->where('resolved', '=', '0')
            ->orderBy('notice_date', 'desc')
            ->get();

        return $maintenance;
    }

    public function getMaintenanceById($id)
    {
        return self::with([
            'diary',
        ])->find($id);
    }
}

Projects/admin/app/Http/Controllers/Admin/MaintenanceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Date;
use App\Helpers\Util;
use App\Http\Controllers\Controller;
use App\Http\Requests\MaintenanceRequest;
use App\Models\Diary;
use App\Models\Maintenance;
use App\Models\Property;

class MaintenanceController extends Controller
{
    public function create(Property $property)
    {
        $maintenance = new Maintenance();

        return view('maintenances.edit', compact('maintenance', 'property'));
    }

    public function store(Property $property, MaintenanceRequest $request)
    {
        $input = $request->all();
        $input['notice_date'] = Date::toMysql($input['notice_date']);
        $input['diary_date'] = Date::toMysql($input['diary_date']);

        if (! isset($input['resolved'])) {
            $input['resolved'] = 0;
        }

        $diary = Diary::create([
            'property_id'   => $property->id,
            'diary_type_id' => 4,
            'diary_title'   => 'Maintenance',
            'date'          => $input['diary_date'],
            'status'        => 0,
        ]);

        $input['diary_id'] = $diary->id;

        $property->maintenance()->create($input);
        Util::addNote($property->id, 'properties', 4, 'Maintenance was Added');

        $data = [
            'id'         => $property->id,
            'status'     => 'ok',
            'controller' => 'properties',
        ];

        return response()->json($data);
    }

    public function edit(Maintenance $maintenance)
    {
        return view('maintenances.edit', compact('maintenance'));
    }

    public function update(Maintenance $maintenance, MaintenanceRequest $request)
    {
        $input = $request->all();
        $input['notice_date'] = Date::toMysql($input['notice_date']);
        $input['diary_date'] = Date::toMysql($input['diary_date']);

        if (! isset($input['resolved'])) {
            $input['resolved'] = 0;
        }

        $diary = Diary::find($input['diary_id']);

        if ($diary) {
            $diary->update([
                'date' => $input['diary_date'],
            ]);
        }

        $maintenance->update($input);
        Util::addNote($maintenance->property_id, 'properties', 4, 'Maintenance was Edited');

        $data = [
            'id'         => $maintenance->property_id,
            'status'     => 'ok',
            'controller' => 'properties',
        ];

        return response()->json($data);
    }
}

Projects/admin/resources/views/properties/includes/maintenances/block.blade.php
<div class="row">

{{--            <header>--}}
{{--                <h2>Maintenance</h2>--}}
{{--                <ul class="data-header-actions">--}}
{{--                    @if(!$read_only)--}}
{{--                        <li>--}}
{{--                            <a href="{{ route('properties.maintenances.create', $property) }}"--}}
{{--                               id="addClientQueryModal"--}}
{{--                               class="modalButton btn btn-alt clientQueryModal">New Maintenance Job</a>--}}
{{--                        </li>--}}
{{--                    @endif--}}
{{--                </ul>--}}
{{--            </header>--}}
<!-- Tab #four -->
    <!-- Second level tabs -->
    <div class="col-md-12">
        @include('properties.includes.maintenances.tabs')

        <div class="tab-content" id="nav-tabContent">
            @if($maintenance->count() == 0)
                No Maintenace Jobs Found.
                @if(!$read_only)
                    {{--                                    <a href="{{ route('properties.maintenances.create', $property) }}"--}}
                    {{--                                       class="maintenanceModal"--}}
                    {{--                                       id="addmaintenanceModal">Add Maintenace Job</a>--}}
                @endif
            @endif
            @foreach($maintenance as $key => $maintenanceJob)

                {{--                                    <header>--}}
                {{--                                        <h2>Due Date - {{Date::dmY($maintenanceJob->notice_date)}}</h2>--}}
                {{--                                        <ul class="data-header-actions">--}}
                {{--                                            @if(!$read_only)--}}
                {{--                                                <li>--}}
                {{--                                                    <a href="{{ route('maintenances.edit', $maintenanceJob) }}"--}}
                {{--                                                       class="btn btn-warning btn-alt maintenanceModal"--}}
                {{--                                                       id="editmaintenanceModal">Edit</a>--}}
                {{--                                                </li>--}}
                {{--                                                <li>--}}
                {{--                                                    <a class="modalButton btn btn-alt btn-primary maintenance-photo-modal" data-toggle="modal" href="#photoModal">Add Photo</a>--}}
                {{--                                                    {{ Form::hidden('maintenance-id', $maintenanceJob->id) }}--}}
                {{--                                                </li>--}}
                {{--                                            @endif--}}
                {{--                                        </ul>--}}
                {{--                                    </header>--}}
                @include('properties.includes.maintenances.inner_section')
            @endforeach
        </div>
    </div>
</div>

Projects/admin/resources/views/properties/includes/maintenances/inner_section.blade.php
<div class="tab-pane fade  @if($key == 0) active show @endif"
     id="nav-maintenance-{{$maintenanceJob->id}}" role="tabpanel"
     aria-labelledby="nav-maintenance-{{$maintenanceJob->id}}-tab">


    <div class="col-12 mb-4 d-flex justify-content-between">
        <div class="dropdown">
            <div class="btn-group mr-2 mb-2">
                <a href="{{route('maintenances.edit',$maintenanceJob->id)}}?property={{$propertyID}}"
                   class="btn add-property btn-outline-primary">Edit</a>
            </div>
        </div>
    </div>

    <div class="row">

        {{--        <div class="maintenance-photo-list-{{$maintenanceJob->id}}">--}}
        <div class="col-md-4">
            <div class="row pt-3 align-items-center">
                <div class="col-sm-5">
                    <small
                        class="text-uppercase text-muted">Details</small>
                </div>
                <div class="col-sm-6 pl-0">
                    <p class="mb-0">{{ Util::showValue($maintenanceJob->notes) }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row pt-3 align-items-center">
                <div class="col-sm-5">
                    <small class="text-uppercase text-muted">Resolved</small>
                </div>
                <div class="col-sm-6 pl-0">
                    <p class="mb-0">
                        {{ Form::checkbox('resolved', '1', $maintenanceJob->resolved, array('disabled' => 'disabled')) }}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row pt-3 align-items-center">
                <div class="col-sm-5">
                    <small
                        class="text-uppercase text-muted">
                    </small>
                </div>
                <div class="col-sm-6 pl-0">
                    <?php $i = 1; ?>
                    @foreach($maintenanceJob->maintenancePhotos as $photo)
                        @include('partials.maintenance-photo-item')
                        <?php $i++; ?>
                    @endforeach
                </div>
            </div>
        </div>

        {{--        </div>--}}
    </div>
</div>


{{--@include('partials.documents_block', [--}}
{{--    'url' => route('ajax.maintenances.documents.create', $maintenanceJob),--}}
{{--    'documents' => $maintenanceJob->documents--}}
{{--])--}}

Projects/admin/resources/views/properties/includes/maintenances/tabs.blade.php
<nav>
    <div class="nav nav-tabs mb-4" id="nav-tab" role="tablist">
        @foreach($maintenance as $key => $maintenanceJob)
            <a class="nav-item nav-link @if($key == 0) active @endif"
               id="nav-maintenance-{{$maintenanceJob->id}}-tab" data-toggle="tab"
               href="#nav-maintenance-{{$maintenanceJob->id}}" role="tab"
               aria-controls="nav-maintenance-{{$maintenanceJob->id}}"
               @if($key == 0) aria-selected="true"
               @else aria-selected="false" @endif >Due Date {{Date::dmY($maintenanceJob->notice_date)}}</a>
        @endforeach
    </div>
</nav>