Projects/price_spotter/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use vipnytt\SitemapParser;
use vipnytt\SitemapParser\Exceptions\SitemapParserException;

Auth::routes();

Route::get('/scrape/{website}', 'Www\HomeController@scrape');
Route::get('/pull/{website}', 'Www\HomeController@pull');

Route::middleware(['auth', 'role:admin'])->namespace('Admin')->domain('admin.'.env('APP_HOST', 'price-spotter.loc'))->group(function () {
    Route::get('/', 'HomeController@home');
    Route::resource('/providers', 'ProviderController');
    Route::resource('/provider-categories', 'ProviderCategoryController');
    Route::resource('/provider-products', 'ProviderProductController');

    Route::resource('/products', 'ProductsController');
    Route::resource('/categories', 'CategoriesController');
});

Route::get('/', 'HomeController@index');

Route::middleware(['auth', 'role:user'])->namespace('Www')->domain('www.'.env('APP_HOST', 'price-spotter.loc'))->group(function () {
    Route::get('/', 'HomeController@home');
});

Route::middleware(['auth', 'role:user'])->group(function () {
    Route::get('/', 'HomeController@home');
});

Route::get('/', 'HomeController@index');

Projects/price_spotter/app/Models/ProviderProduct.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class ProviderProduct extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'reference', 'url', 'provider_id', 'parent_id', 'product_id', 'archived', 'checked_at', 'checked_by',
        'created_by', 'updated_by',
    ];

    /**
     * Get the Provider that owns the provider_category.
     */
    public function provider()
    {
        return $this->belongsTo('App\Models\Provider');
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'checked_by');
    }

    /**
     * Get all of the product's exceptions.
     */
    public function exceptions()
    {
        return $this->morphMany('App\Models\Exception', 'exceptionable');
    }
}

Projects/price_spotter/app/Http/Controllers/Admin/ProviderProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\ProviderProduct;
use Illuminate\Http\Request;

class ProviderProductController extends Controller
{
    const PAGINATE_COUNT = 10;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = ProviderProduct::paginate(self::PAGINATE_COUNT);

        return view('admin.providerProduct.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $providerProduct = ProviderProduct::findOrFail($id);

        return view('admin.providerProduct.show', compact('providerProduct'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

Projects/price_spotter/resources/views/admin/providerProduct/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="section section-sm">
        <div class="container">
            <!-- Title  -->
            <div class="row">
                <div class="col-12 mb-5 d-flex justify-content-between">
                    <div>
                        <h5 class="font-weight-bold">Provider Products</h5>
                    </div>
                    <div class="dropdown">
                        <div class="btn-group mr-2 mb-2">
                            <a class="btn add-property btn-outline-primary">Add Property</a>
                        </div>
                        <div class="btn-group mr-2 mb-2">
                            <select class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                                <option>All properties</option>
                                <option>Active</option>
                                <option>Disposed</option>
                            </select>
                        </div>

                    </div>
                </div>
            </div>
            <!-- End of Title -->
            <div class="row">
                <div class="col-md-12">
                    <div class="mb-5">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Reference</th>
                                <th scope="col">Url</th>
                                <th scope="col">Provider</th>
                                <th scope="col">Approved</th>
                                <th scope="col">Archived</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($products as $product)
                                <tr>
                                    <td><a href="{{route('provider-products.show', $product->id)}}">{{$product->name ?? ' - '}}</a></td>
                                    <td>{{$product->reference ?? ' - '}}</td>
                                    <td>{{$product->url}}</td>
                                    <td>{{$product->provider->name}}</td>
                                    <td>
                                        {{!is_null($product->checked_at) ? $product->user->name . ' ' . \Carbon\Carbon::parse($product->checked_at)->format('d/m/y') : 'No'}}
                                    </td>
                                    <td>{{$product->archived ? 'Yes': 'No'}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        <nav class="property-list-pagination" aria-label="Page navigation example">
                            <span>Showing {{$products->firstItem()}} to {{$products->lastItem()}} of {{$products->total()}} entries</span>
                            {{$products->links()}}
                        </nav>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

Projects/price_spotter/resources/views/admin/providerProduct/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="section section-sm">
        <div class="container">
            <!-- Title  -->
            <div class="row">
                <div class="col-12 mb-5 d-flex justify-content-between">


                    @dump($providerProduct->toArray())


                </div>
            </div>
        </div>
    </div>

@endsection