Projects/admin/routes/web.php
    Route::resource('landlords.contacts', 'ContactController')->only(['create', 'store']);
    Route::resource('landlords.notes', 'NoteController')->only('store');

    Route::get('clients/{client}/audit-registers-partial', 'ClientController@viewAuditRegistersPartial');
    Route::resource('clients', 'ClientController');
    Route::resource('clients.contacts', 'ContactController')->only(['create', 'store']);
    Route::resource('clients.notes', 'NoteController')->only('store');

    Route::resource('contacts', 'ContactController');
    Route::resource('contacts.notes', 'NoteController')->only('store');

    Route::resource('payments', 'PaymentController')->only(['index', 'edit', 'update', 'destroy']);
    Route::resource('utilities', 'UtilityController')->only(['index', 'edit', 'update', 'destroy']);
    Route::resource('payments.documents', 'DocumentController')->only('store');
    Route::get('ajax/payments/{payment}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.payments.documents.create');

    Route::resource('rents', 'RentController')->only(['edit', 'update', 'destroy']);

    Route::resource('service-charges', 'ServiceChargeController');
    Route::resource('service-charges.documents', 'DocumentController')->only('store')->parameters([
        'service-charges' => 'serviceCharge',
    ]);
    Route::get('ajax/service-charges/{serviceCharge}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.service-charges.documents.create');

    Route::resource('rent-reviews', 'RentReviewController')->only(['edit', 'update']);
    Route::resource('rent-reviews.documents', 'DocumentController')->only('store')->parameters([
        'rent-reviews' => 'rentReview',
    ]);
    Route::get('ajax/rent-reviews/{rentReview}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.rent-reviews.documents.create');

    Route::resource('breaks', 'BreakController')->only(['edit', 'update', 'destroy']);
    Route::resource('breaks.documents', 'DocumentController')->only('store');
    Route::get('ajax/breaks/{break}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.breaks.documents.create');

    Route::resource('client-queries', 'ClientQueryController')->only(['edit', 'update']);
    Route::resource('client-queries.documents', 'DocumentController')->only('store')->parameters([
        'client-queries' => 'clientQuery',
    ]);
    Route::get('ajax/client-queries/{clientQuery}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.client-queries.documents.create');

    Route::resource('insurances', 'InsuranceController')->only(['edit', 'update', 'destroy']);
    Route::resource('insurances.documents', 'DocumentController')->only('store');
    Route::get('ajax/insurances/{insurance}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.insurances.documents.create');

    Route::resource('maintenances', 'MaintenanceController')->only(['edit', 'update']);
    Route::resource('maintenances.photos', 'MaintenancePhotoController')->only('store');
    Route::resource('maintenances.documents', 'DocumentController')->only('store');
    Route::get('ajax/maintenances/{maintenance}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.maintenances.documents.create');

    Route::resource('documents', 'DocumentController');

    Route::get('ajax/suppliers/{supplier}/contacts/select', 'SupplierController@getContactsSelectPartial')
        ->name('ajax.suppliers.contacts.select');
    Route::resource('suppliers', 'SupplierController');

    Route::get('ajax/suppliers/{supplier}/contacts/create', 'ContactController@ajaxCreate')
        ->name('ajax.suppliers.contacts.create');
    Route::resource('suppliers.contacts', 'ContactController')->only(['create', 'store']);
    Route::resource('suppliers.notes', 'NoteController')->only('store');

    Route::resource('administrators', 'AdministratorController');
    Route::resource('administrators.contacts', 'ContactController')->only(['create', 'store']);

    Route::resource('audit-registers', 'AuditRegisterController');

    Route::resource('claims', 'ClaimController');
    Route::resource('claims.notes', 'NoteController')->only('store');

    Route::get('claim-types/{claimType}/subtypes-partial', 'ClaimTypeController@viewSubtypesPartial');

    Route::resource('auditors', 'AuditorController');

    Route::resource('settings', 'SettingsController')->only('index');
    Route::post('settings/type', 'SettingsController@postType')->name('settings.type');
    Route::put('settings/type', 'SettingsController@updateType')->name('settings.update-type');
    Route::delete('settings/type', 'SettingsController@deleteType')->name('settings.delete-type');

    Route::resource('settings/currencies', 'CurrencyController');
    Route::get('settings/currencies/{currency}/delete', 'CurrencyController@delete');

    Route::resource('settings/payment-types', 'PaymentTypeController');
    Route::get('settings/payment-types/{paymentType}/delete', 'PaymentTypeController@delete');

    Route::resource('settings/claim-subtypes', 'ClaimSubtypeController');
    Route::get('settings/claim-subtypes/{claimSubtype}/delete', 'ClaimSubtypeController@delete');

    Route::resource('settings/staff', 'SettingsStaffController')->except('destroy')->middleware('superAdmin');

    Route::get('index-table', 'SettingsController@indexTable');
    Route::get('show-type/{id}', 'SettingsController@showType');
    Route::post('type-store', 'SettingsController@storeType')->name('type.store');
    Route::put('type-update', 'SettingsController@updateType')->name('type.update');
    Route::delete('type-delete', 'SettingsController@destroyType')->name('type.delete');

    // issue with this routes
    Route::middleware(['superAdmin'])->group(function () {
        Route::get('/account/settings', 'SettingsController@index')->name('account.settings');
        Route::get('/account/settings/user/{id}', 'SettingsController@userDetails')->name('user.details');
        Route::get('/account/settings/user/edit/{id}', 'SettingsController@userDetailsEdit')->name('user.details.edit');
    });
    Route::get('account/switch-client', 'SwitchClientController@switchClient')->name('switch.client');
    Route::post('account/settings/switch-client', 'SwitchClientController@saveSwitchClient')->name('save.current.client');

    // REPORTS
    Route::middleware(['report'])->group(function () {
        Route::get('reports/new/{type}', 'ReportController@getCommonTable');
        Route::get('reports/download/zip', 'ReportController@downloadAsZip')->name('reports.download.zip');

        Route::get('reports/master-spreadsheet', 'ReportController@getMasterSpreadsheet')
            ->name('reports.master-spreadsheet');
        Route::get('reports/rent-review', 'ReportController@getRentReview')->name('reports.rent-review');
        Route::get('reports/rent-review-csv', 'ReportCsvController@getRentReviewCSV')->name('reports.rent-review-csv');
        Route::get('reports/lease-expiry', 'ReportController@getLeaseExpiry')->name('reports.lease-expiry');

        Route::get('reports/lease-expiry-csv', 'ReportCsvController@getLeaseExpiryCSV')->name('reports.lease-expiry-csv');
        Route::get('reports/rateable-value', 'ReportController@getRateableValue')->name('reports.rateable-value');
        Route::get('reports/rateable-value-csv', 'ReportCsvController@getRateableValueCSV')
            ->name('reports.rateable-value-csv');
        Route::get('reports/break-option', 'ReportController@getBreakOption')->name('reports.break-option');
        Route::get('reports/break-option-csv', 'ReportCsvController@getBreakOptionCSV')->name('reports.break-option-csv');
        Route::get('reports/condition', 'ReportController@getCondition')->name('reports.condition');
        Route::get('reports/condition-csv', 'ReportCsvController@getConditionCSV')->name('reports.condition-csv');
        Route::get('reports/document-checklist', 'ReportController@getDocumentChecklist')
            ->name('reports.document-checklist');
        Route::get('reports/document-checklist-csv', 'ReportCsvController@getDocumentChecklistCSV')
            ->name('reports.document-checklist-csv');
        Route::get('reports/maintenance', 'ReportController@getMaintenance')->name('reports.maintenance');
        Route::get('reports/maintenance-csv', 'ReportCsvController@getMaintenanceCSV')->name('reports.maintenance-csv');
        Route::get('reports/rental-liability', 'ReportController@getRentalLiability')->name('reports.rental-liability');
        Route::get('reports/rental-liability-csv', 'ReportCsvController@getRentalLiabilityCSV')
            ->name('reports.rental-liability-csv');
        Route::get('reports/budget', 'ReportController@getBudget')->name('reports.budget');
        Route::get('reports/annual-service-charge-csv', 'ReportCsvController@getAnnualServiceChargeCSV')
            ->name('reports.annual-service-charge-csv');
        Route::get('reports/actual', 'ReportController@getActual')->name('reports.actual');
        Route::get('reports/missing/{type}', 'ReportController@getMissing')->name('reports.missing');
        Route::get('reports/missingrecs/{type}', 'ReportController@getMissing')->name('reports.missingrecs');
        Route::get('reports/missing-payments-csv/{type}', 'ReportCsvController@getMissingPaymentsCSV')
            ->name('reports.missing-payments-csv');
        Route::get('reports/service-charge', 'ReportController@allRecentChargesForPropertiesReport')
            ->name('reports.service-charge');
        Route::get('reports/service-charge-csv', 'ReportCsvController@allRecentChargesForPropertiesCSV')
            ->name('reports.service-charge-csv');
        Route::get('reports/on-account', 'ReportController@quarterlyServiceChargeReport')->name('reports.on-account');
        Route::get('reports/quarter-budget-csv', 'ReportCsvController@getQuarterBudgetCSV')

Projects/admin/app/Models/Supplier.php
<?php

namespace App\Models;

use App\Presenters\SupplierPresenter;
use App\Traits\CreateAndUpdateTrait;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laracasts\Presenter\PresentableTrait;
use Spatie\Searchable\Searchable;
use Spatie\Searchable\SearchResult;

/**
 * Class Suppliers.
 * @version October 29, 2019, 3:32 am UTC
 *
 * @property \App\Models\Address address
 * @property \App\Models\User createdBy
 * @property \App\Models\User updatedBy
 * @property \Illuminate\Database\Eloquent\Collection payments
 * @property string name
 * @property string telephone
 * @property string fax
 * @property string email
 * @property int address_id
 * @property int created_by
 * @property int updated_by
 */
class Supplier extends BaseModel implements Searchable
{
    use SoftDeletes, CreateAndUpdateTrait, PresentableTrait;

    public $table = 'suppliers';
    public $createContactRoute = 'suppliers.contacts.store';
    public $contactElementName = 'contact_id';
    protected $presenter = SupplierPresenter::class;

    public $searchableType = 'Supplier';

    public $fillable = [
        'name',
        'telephone',
        'fax',
        'email',
        'address_id',
        'created_by',
        'updated_by',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'telephone' => 'string',
        'fax' => 'string',
        'email' => 'string',
        'address_id' => 'integer',
        'created_by' => 'integer',
        'updated_by' => 'integer',
    ];

    public function getSearchResult(): SearchResult
    {
        $url = route('suppliers.show', $this->id);

        return new \Spatie\Searchable\SearchResult(
            $this,
            $this->name.', '.$this->email,
            $url
        );
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function address()
    {
        return $this->belongsTo(Address::class, 'address_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function payments()
    {
        return $this->hasMany(Payment::class, 'supplier_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function updatedBy()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    public function contacts()
    {
        return $this->morphMany(Contact::class, 'contactable');
    }

    public function getShowUrl()
    {
        return route('suppliers.show', $this);
    }

    public function getShowName()
    {
        return $this->name;
    }

    public function createNote($data)
    {
        $data['object_type_id'] = 6;
        $data['object_id'] = $this->id;

        Note::create($data);
    }

    public function getNotes()
    {
        return Note::where('object_type_id', 6)->where('object_id', $this->id)->get();
    }

    public function getMainContactAttribute()
    {
        return $this->contacts()->first();
    }
}

Projects/admin/app/Http/Controllers/Admin/SupplierController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\SupplierRequest;
use App\Models\Address;
use App\Models\NoteType;
use App\Models\Supplier;

class SupplierController extends Controller
{
    protected $user;

    const PAGINATE_COUNT = 10;

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->user = auth()->user();

            return $next($request);
        });
    }

    public function index()
    {
        $read_only = $this->user->isClient();
        $suppliers = Supplier::paginate(self::PAGINATE_COUNT);

        return view('suppliers.index', compact('suppliers', 'read_only'));
    }

    public function create()
    {
        $supplier = new Supplier();
        $address = new Address();

        return view('suppliers.edit', compact('supplier', 'address'));
    }

    public function store(SupplierRequest $request)
    {
        $input = $request->all();
        $address = Address::create($input['address']);
        $input['address_id'] = $address->id;
        $supplier = Supplier::create($input);

        $supplier->contacts()->create($input['contact']);

        $supplier->createNote([
            'note_type_id' => 1,
            'note_text'    => 'Supplier was Added',
        ]);

        $data = [
            'id'         => $supplier->id,
            'status'     => 'ok',
            'controller' => 'suppliers',
        ];

        return response()->json($data);
    }

    public function show(Supplier $supplier)
    {
        $read_only = $this->user->isClient();
        $notes = $supplier->getNotes();
        $noteTypes = (new NoteType)->toDropdown();

        return view('suppliers.show', compact('supplier', 'read_only', 'notes', 'noteTypes'));
    }

    public function edit(Supplier $supplier)
    {
        $address = $supplier->address;

        return view('suppliers.edit', compact('supplier', 'address'));
    }

    public function update(Supplier $supplier, SupplierRequest $request)
    {
        $supplier->address->update($request->get('address'));
        $supplier->update($request->all());

        $supplier->createNote([
            'note_type_id' => 1,
            'note_text'    => 'Supplier was Edited',
        ]);

        $data = [
            'id'         => $supplier->id,
            'status'     => 'ok',
            'controller' => 'suppliers',
        ];

        return response()->json($data);
    }

    public function getContactsSelectPartial(Supplier $supplier)
    {
        $contacts = $supplier->contacts;
        $contactId = null;
        $elementName = 'contact_id';
        $view = view('partials.edit_contacts_partial', compact('contacts', 'contactId', 'elementName'))->render();

        return response()->json(compact('view'));
    }
}

Projects/admin/resources/views/suppliers/includes/form.blade.php
<div class="container-fluid">
    <div class="row align-items-center justify-content-center">
        <div class="col-12 col-md-5 col-lg-4 order-md-1">
            <div class="mb-5 text-center">
                <h6 class="h3">{{$title}}</h6>
                <div class="dropdown-divider"></div>
            </div>
            <div id='error-message'></div>
            <form method="POST"
                  action="{{ $supplier->id ? route('suppliers.update', $supplier) : route('suppliers.store') }}"
                  class="form-horizontal" id="create-supplier">
                {{ csrf_field() }}

                @if($supplier->id)
                    {{ method_field('PUT') }}
                @endif

                <div id="name" class="control-group">
                    <label for="name" class="control-label">Name</label>
                    <div class="form-group controls">
                        <input type="text" name="name" id="name"
                               class="form-control  @error('name') invalid-input @enderror"
                               value="{{ $supplier->name }}">
                        <span id="name" class="help-block invalid-text"></span>
                    </div>
                </div>

                @if (!$supplier->id)
                    <div id="contact-first_name" class="control-group">
                        <label for="contact-first_name" class="control-label">Contact First Name</label>
                        <div class="form-group">
                            <input type="text" name="contact[first_name]" id="contact-first_name"
                                   class="form-control @error('contact.surname') invalid-input @enderror">
                            <span id="contact-first_name" class="help-block invalid-text"></span>
                        </div>
                    </div>
                    <div id="contact-surname" class="control-group">
                        <label for="contact-surname" class="control-label">Contact Surname</label>
                        <div class="form-group">
                            <input type="text" name="contact[surname]" id="contact-surname"
                                   class="form-control @error('contact.surname') invalid-input @enderror">
                            <span id="contact-surname" class="help-block invalid-text"></span>
                        </div>
                    </div>
                @endif

                <div id="address-address_1" class="control-group">
                    <label for="address-address_1" class="control-label">Address Line 1</label>
                    <div class="form-group">
                        <input type="text"
                               name="address[address_1]"
                               id="address-address_1"
                               class="form-control @error('address.address_1') invalid-input @enderror()"
                               value="{{ $address->address_1 }}">
                        <span id="address-address_1" class="help-block"></span>
                    </div>
                </div>

                <div id="address-address_2" class="control-group">
                    <label for="address-address_2" class="control-label">Address Line 2</label>
                    <div class="form-group">
                        <input type="text"
                               name="address[address_2]"
                               id="address-address_2"
                               class="form-control"
                               value="{{ $address->address_2 }}">
                        <span id="address_2" class="help-block invalid-text"></span>
                    </div>
                </div>

                <div id="town" class="control-group">
                    <label for="town" class="control-label">Town</label>
                    <div class="form-group">
                        <input type="text" name="address[town]" id="town" class="form-control"
                               value="{{ $address->town }}">
                        <span id="town" class="help-block"></span>
                    </div>
                </div>

                <div id="county" class="control-group">
                    <label for="county" class="control-label">County</label>
                    <div class="form-group">
                        <input type="text"
                               name="address[county]"
                               id="county"
                               class="form-control"
                               value="{{ $address->county }}">
                        <span id="county" class="help-block"></span>
                    </div>
                </div>

                <div id="address-post_code" class="control-group">
                    <label for="address-post_code" class="control-label">Post Code</label>
                    <div class="form-group">
                        <input type="text"
                               name="address[post_code]"
                               id="address-post_code"
                               class="form-control  @error('address.post_code') invalid-input @enderror"
                               value="{{ $address->post_code }}">
                        <span id="address-post_code" class="help-block invalid-text"></span>
                    </div>
                </div>

                <div id="telephone" class="control-group">
                    <label for="telephone" class="control-label">Telephone Number</label>
                    <div class="form-group">
                        <input type="text"
                               name="telephone"
                               id="telephone"
                               class="form-control @error('telephone') invalid-input @enderror"
                               value="{{ $supplier->telephone }}">
                        <span id="telephone" class="help-block invalid-text"></span>
                    </div>
                </div>

                <div id="fax" class="control-group">
                    <label for="fax" class="control-label">Fax Number</label>
                    <div class="form-group">
                        <input type="text" name="fax" id="fax" class="form-control" value="{{ $supplier->fax }}">
                        <span id="fax" class="help-block invalid-text"></span>
                    </div>
                </div>

                <div id="email" class="control-group">
                    <label for="email" class="control-label">Email</label>
                    <div class="form-group">
                        <input type="text" name="email" id="email" class="form-control" value="{{ $supplier->email }}">
                        <span id="email" class="help-block invalid-text"></span>
                    </div>
                </div>

                <div class="form-actions">
                    <button id="save-supplier" class="btn btn-block mr-2 mb-2 btn-outline-primary" type="submit">
                        Save Changes
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@push('js')
    <script src="{{ asset('js/moved/libs/jquery.form.js') }}"></script>
@endpush