Projects/admin/routes/web.php
    Route::resource('contacts.notes', 'NoteController')->only('store');

    Route::resource('payments', 'PaymentController')->only(['index', 'edit', 'update', 'destroy']);
    Route::resource('utilities', 'UtilityController')->only(['index', 'edit', 'update', 'destroy']);
    Route::resource('payments.documents', 'DocumentController')->only('store');
    Route::get('ajax/payments/{payment}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.payments.documents.create');

    Route::resource('rents', 'RentController')->only(['edit', 'update', 'destroy']);

    Route::resource('service-charges', 'ServiceChargeController');
    Route::resource('service-charges.documents', 'DocumentController')->only('store')->parameters([
        'service-charges' => 'serviceCharge',
    ]);
    Route::get('ajax/service-charges/{serviceCharge}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.service-charges.documents.create');

    Route::resource('rent-reviews', 'RentReviewController')->only(['edit', 'update']);
    Route::resource('rent-reviews.documents', 'DocumentController')->only('store')->parameters([
        'rent-reviews' => 'rentReview',
    ]);
    Route::get('ajax/rent-reviews/{rentReview}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.rent-reviews.documents.create');

    Route::resource('breaks', 'BreakController')->only(['edit', 'update', 'destroy']);
    Route::resource('breaks.documents', 'DocumentController')->only('store');
    Route::get('ajax/breaks/{break}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.breaks.documents.create');

    Route::resource('client-queries', 'ClientQueryController')->only(['edit', 'update']);
    Route::resource('client-queries.documents', 'DocumentController')->only('store')->parameters([
        'client-queries' => 'clientQuery',
    ]);
    Route::get('ajax/client-queries/{clientQuery}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.client-queries.documents.create');

    Route::resource('insurances', 'InsuranceController')->only(['edit', 'update', 'destroy']);
    Route::resource('insurances.documents', 'DocumentController')->only('store');
    Route::get('ajax/insurances/{insurance}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.insurances.documents.create');

    Route::resource('maintenances', 'MaintenanceController')->only(['edit', 'update']);
    Route::resource('maintenances.photos', 'MaintenancePhotoController')->only('store');
    Route::resource('maintenances.documents', 'DocumentController')->only('store');
    Route::get('ajax/maintenances/{maintenance}/documents/create', 'DocumentController@ajaxCreate')
        ->name('ajax.maintenances.documents.create');

    Route::resource('documents', 'DocumentController');

    Route::get('ajax/suppliers/{supplier}/contacts/select', 'SupplierController@getContactsSelectPartial')
        ->name('ajax.suppliers.contacts.select');
    Route::resource('suppliers', 'SupplierController');

    Route::get('ajax/suppliers/{supplier}/contacts/create', 'ContactController@ajaxCreate')
        ->name('ajax.suppliers.contacts.create');
    Route::resource('suppliers.contacts', 'ContactController')->only(['create', 'store']);
    Route::resource('suppliers.notes', 'NoteController')->only('store');

    Route::resource('administrators', 'AdministratorController');
    Route::resource('administrators.contacts', 'ContactController')->only(['create', 'store']);

    Route::resource('audit-registers', 'AuditRegisterController');

    Route::resource('claims', 'ClaimController');
    Route::resource('claims.notes', 'NoteController')->only('store');

    Route::get('claim-types/{claimType}/subtypes-partial', 'ClaimTypeController@viewSubtypesPartial');

    Route::resource('auditors', 'AuditorController');

    Route::resource('settings', 'SettingsController')->only('index');
    Route::post('settings/type', 'SettingsController@postType')->name('settings.type');
    Route::put('settings/type', 'SettingsController@updateType')->name('settings.update-type');
    Route::delete('settings/type', 'SettingsController@deleteType')->name('settings.delete-type');

    Route::resource('settings/currencies', 'CurrencyController');
    Route::get('settings/currencies/{currency}/delete', 'CurrencyController@delete');

    Route::resource('settings/payment-types', 'PaymentTypeController');
    Route::get('settings/payment-types/{paymentType}/delete', 'PaymentTypeController@delete');

    Route::resource('settings/claim-subtypes', 'ClaimSubtypeController');
    Route::get('settings/claim-subtypes/{claimSubtype}/delete', 'ClaimSubtypeController@delete');

    Route::resource('settings/staff', 'SettingsStaffController')->except('destroy')->middleware('superAdmin');

    Route::get('index-table', 'SettingsController@indexTable');
    Route::get('show-type/{id}', 'SettingsController@showType');
    Route::post('type-store', 'SettingsController@storeType')->name('type.store');
    Route::put('type-update', 'SettingsController@updateType')->name('type.update');
    Route::delete('type-delete', 'SettingsController@destroyType')->name('type.delete');

    // issue with this routes
    Route::middleware(['superAdmin'])->group(function () {
        Route::get('/account/settings', 'SettingsController@index')->name('account.settings');
        Route::get('/account/settings/user/{id}', 'SettingsController@userDetails')->name('user.details');
        Route::get('/account/settings/user/edit/{id}', 'SettingsController@userDetailsEdit')->name('user.details.edit');
    });
    Route::get('account/switch-client', 'SwitchClientController@switchClient')->name('switch.client');
    Route::post('account/settings/switch-client', 'SwitchClientController@saveSwitchClient')->name('save.current.client');

    // REPORTS
    Route::middleware(['report'])->group(function () {
        Route::get('reports/new/{type}', 'ReportController@getCommonTable');
        Route::get('reports/download/zip', 'ReportController@downloadAsZip')->name('reports.download.zip');

        Route::get('reports/master-spreadsheet', 'ReportController@getMasterSpreadsheet')
            ->name('reports.master-spreadsheet');
        Route::get('reports/rent-review', 'ReportController@getRentReview')->name('reports.rent-review');
        Route::get('reports/rent-review-csv', 'ReportCsvController@getRentReviewCSV')->name('reports.rent-review-csv');
        Route::get('reports/lease-expiry', 'ReportController@getLeaseExpiry')->name('reports.lease-expiry');

        Route::get('reports/lease-expiry-csv', 'ReportCsvController@getLeaseExpiryCSV')->name('reports.lease-expiry-csv');
        Route::get('reports/rateable-value', 'ReportController@getRateableValue')->name('reports.rateable-value');
        Route::get('reports/rateable-value-csv', 'ReportCsvController@getRateableValueCSV')
            ->name('reports.rateable-value-csv');
        Route::get('reports/break-option', 'ReportController@getBreakOption')->name('reports.break-option');
        Route::get('reports/break-option-csv', 'ReportCsvController@getBreakOptionCSV')->name('reports.break-option-csv');
        Route::get('reports/condition', 'ReportController@getCondition')->name('reports.condition');
        Route::get('reports/condition-csv', 'ReportCsvController@getConditionCSV')->name('reports.condition-csv');
        Route::get('reports/document-checklist', 'ReportController@getDocumentChecklist')
            ->name('reports.document-checklist');
        Route::get('reports/document-checklist-csv', 'ReportCsvController@getDocumentChecklistCSV')
            ->name('reports.document-checklist-csv');
        Route::get('reports/maintenance', 'ReportController@getMaintenance')->name('reports.maintenance');
        Route::get('reports/maintenance-csv', 'ReportCsvController@getMaintenanceCSV')->name('reports.maintenance-csv');
        Route::get('reports/rental-liability', 'ReportController@getRentalLiability')->name('reports.rental-liability');
        Route::get('reports/rental-liability-csv', 'ReportCsvController@getRentalLiabilityCSV')
            ->name('reports.rental-liability-csv');
        Route::get('reports/budget', 'ReportController@getBudget')->name('reports.budget');
        Route::get('reports/annual-service-charge-csv', 'ReportCsvController@getAnnualServiceChargeCSV')
            ->name('reports.annual-service-charge-csv');
        Route::get('reports/actual', 'ReportController@getActual')->name('reports.actual');
        Route::get('reports/missing/{type}', 'ReportController@getMissing')->name('reports.missing');
        Route::get('reports/missingrecs/{type}', 'ReportController@getMissing')->name('reports.missingrecs');
        Route::get('reports/missing-payments-csv/{type}', 'ReportCsvController@getMissingPaymentsCSV')
            ->name('reports.missing-payments-csv');
        Route::get('reports/service-charge', 'ReportController@allRecentChargesForPropertiesReport')
            ->name('reports.service-charge');
        Route::get('reports/service-charge-csv', 'ReportCsvController@allRecentChargesForPropertiesCSV')
            ->name('reports.service-charge-csv');
        Route::get('reports/on-account', 'ReportController@quarterlyServiceChargeReport')->name('reports.on-account');
        Route::get('reports/quarter-budget-csv', 'ReportCsvController@getQuarterBudgetCSV')
            ->name('reports.quarter-budget-csv');
        Route::get('reports/get-document-tables', 'ReportController@getDocumentTables')
            ->name('reports.get-document-tables');
        Route::get('reports/approvals', 'ReportController@getApprovals')->name('reports.approvals');
        Route::get('reports/approvals-pdf', 'ReportController@getApprovalsPDF')->name('reports.approvals-pdf');
        Route::get('reports/properties-pdf', 'ReportController@getPropertiesPDF')->name('reports.properties-pdf');

Projects/admin/app/Models/Administrator.php
<?php

namespace App\Models;

/**
 * Class Administrators.
 * @version October 29, 2019, 3:31 am UTC
 *
 * @property \App\Models\Address address
 * @property \Illuminate\Database\Eloquent\Collection clients
 * @property string name
 * @property int address_id
 * @property int created_by
 * @property int updated_by
 */
class Administrator extends BaseModel
{
    public $table = 'administrators';

    public $fillable = [
        'name',
        'address_id',
        'created_by',
        'updated_by',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'address_id' => 'integer',
        'created_by' => 'integer',
        'updated_by' => 'integer',
    ];

    /**
     * Validation rules.
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'address_id' => 'required',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function updatedBy()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function address()
    {
        return $this->belongsTo(Address::class, 'address_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function clients()
    {
        return $this->hasMany(Client::class, 'administrator_id');
    }
}

Projects/admin/app/Http/Controllers/Admin/AdministratorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AdministratorRequest;
use App\Models\Address;
use App\Models\Administrator;

class AdministratorController extends Controller
{
    protected $user;

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->user = auth()->user();

            return $next($request);
        });
    }

    public function index()
    {
        $read_only = $this->user->read_only;
        $administrators = Administrator::select(['id', 'name'])->get();

        return view('administrators.index', compact('administrators', 'read_only'));
    }

    public function create()
    {
        $administrator = new Administrator();
        $address = new Address();

        return view('administrators.edit', compact('administrator', 'address'));
    }

    public function store(AdministratorRequest $request)
    {
        $input = $request->all();
        $address = Address::create($input['address']);
        $input['address_id'] = $address->id;
        $administrator = Administrator::create($input);

        $administrator->contacts()->create($input['contact']);

        $data = [
            'id'         => $administrator->id,
            'status'     => 'ok',
            'controller' => 'administrators',
        ];

        return response()->json($data);
    }

    public function show(Administrator $administrator)
    {
        $read_only = $this->user->read_only;

        return view('administrators.show', compact('administrator', 'read_only'));
    }

    public function edit(Administrator $administrator)
    {
        $address = $administrator->address;

        return view('administrators.edit', compact('administrator', 'address'));
    }

    public function update(Administrator $administrator, AdministratorRequest $request)
    {
        $address = $request->get('address');
        if ($address) {
            $administrator->address->update($address);
        }

        $administrator->update($request->all());

        $data = [
            'id'         => $administrator->id,
            'status'     => 'ok',
            'controller' => 'administrators',
        ];

        return response()->json($data);
    }
}

Projects/admin/resources/views/administrators/includes/form.blade.php
<fieldset>
    <div id='error-message'></div>

    <form method="POST"
          action="{{ $administrator->id ? route('administrators.update', $administrator) : route('administrators.store') }}"
          class="form-horizontal"
          id="create-administrator">
        {{ csrf_field() }}

        @if($administrator->id)
            {{ method_field('PUT') }}
        @endif

        <div id="name" class="control-group">
            <label for="name" class="control-label">Name</label>
            <div class="controls">
                <input type="text" name="name" id="name" class="input-medium" value="{{ $administrator->name }}">
                <span id="name" class="help-block"></span>
            </div>
        </div>

        @if (!$administrator->id)
            <div id="contact-first_name" class="control-group">
                <label for="contact-first_name" class="control-label">Contact First Name</label>
                <div class="controls">
                    <input type="text" name="contact[first_name]" id="contact-first_name" class="input-medium">
                    <span id="contact-first_name" class="help-block"></span>
                </div>
            </div>
            <div id="contact-surname" class="control-group">
                <label for="contact-surname" class="control-label">Contact Surname</label>
                <div class="controls">
                    <input type="text" name="contact[surname]" id="contact-surname" class="input-medium">
                    <span id="contact-surname" class="help-block"></span>
                </div>
            </div>
            <div id="contact-email" class="control-group">
                <label for="contact-email" class="control-label">Contact Email</label>
                <div class="controls">
                    <input type="text" name="contact[email]" id="contact-email" class="input-medium">
                    <span id="contact-email" class="help-block"></span>
                </div>
            </div>
        @endif

        <div id="address-address_1" class="control-group">
            <label for="address_1" class="control-label">Address Line 1</label>
            <div class="controls">
                <input type="text"
                       name="address[address_1]"
                       id="address_1"
                       class="input-xlarge"
                       value="{{ $address->address_1 }}">
                <span id="address-address_1" class="help-block"></span>
            </div>
        </div>

        <div id="address-address_2" class="control-group">
            <label for="address_2" class="control-label">Address Line 2</label>
            <div class="controls">
                <input type="text"
                       name="address[address_2]"
                       id="address_2"
                       class="input-xlarge"
                       value="{{ $address->address_2 }}">
                <span id="address-address_2" class="help-block"></span>
            </div>
        </div>

        <div id="address-town" class="control-group">
            <label for="town" class="control-label">Town</label>
            <div class="controls">
                <input type="text" name="address[town]" id="town" class="input-medium" value="{{ $address->town }}">
                <span id="address-town" class="help-block"></span>
            </div>
        </div>

        <div id="address-county" class="control-group">
            <label for="county" class="control-label">County</label>
            <div class="controls">
                <input type="text"
                       name="address[county]"
                       id="county"
                       class="input-medium"
                       value="{{ $address->county }}">
                <span id="address-county" class="help-block"></span>
            </div>
        </div>

        <div id="address-post_code" class="control-group">
            <label for="post_code" class="control-label">Post Code</label>
            <div class="controls">
                <input type="text"
                       name="address[post_code]"
                       id="post_code"
                       class="input-small"
                       value="{{ $address->post_code }}">
                <span id="address-post_code" class="help-block"></span>
            </div>
        </div>

        <div class="form-actions">
            <button id="save-administrator" class="btn btn-large btn-primary" type="submit">
                Save Changes
            </button>
        </div>
    </form>
</fieldset>

@push('js')
    <script src="{{ asset('js/moved/libs/jquery.form.js') }}"></script>
@endpush